kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: event-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: event-reader
    #namespace: default
roleRef:
  kind: Role
  name: event-reader-role
  apiGroup: rbac.authorization.k8s.io
  #